name: Version Patch

on:
  push:
    branches:
      - main

jobs:
  version_patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'  # adjust to your Node.js version

      - name: Set up Git
        run: |
          git config --global user.email "daominhwysi@gmail.com"
          git config --global user.name "DaQMinh"

      - name: Install dependencies
        run: npm install

      - name: Bump version
        run: npm version patch

      - name: Push changes
        run: |
          git push --follow-tags
