name: Publish

on:
  push:
    branches:
      - main

jobs:
  version_patch_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # adjust to your Node.js version

      - name: Set up Git
        run: |
          git config --global user.email "daominhwysi@gmail.com"
          git config --global user.name "DaQMinh"

      - name: Install dependencies
        run: npm install

      - name: Bump version
        run: npm version patch

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}  # Ensure you have this token set in your repository secrets
