name: Publish

on:
  push:
    branches:
      - main  # adjust this to your main branch name

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Update version and publish
        run: |
          # Update the version (e.g., patch, minor, major)
          npm version patch
          
          # Authenticate with npm (replace <NPM_TOKEN> with your npm token)
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          
          # Publish to npm
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
